blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, by_tag, by_category

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path
from .views import HomeView, ShopView, CheckoutView, OrderSummaryView, ItemDetailView, about, contact,add_to_cart, add_single_item_to_cart, \
     remove_from_cart, remove_single_item_from_cart, PaymentView, addCouponView, RequestRefundView, send_email, subscribe_newsletter

app_name = 'core'

urlpatterns = [
     path('', HomeView.as_view(), name='home'),
     path('shop/', ShopView.as_view(), name='shop'),
     path('product/<slug>/', ItemDetailView.as_view(), name='product'),

     path('add-single-item-to-cart/<slug>/', add_single_item_to_cart, name='add-single-item-to-cart'),
     path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
     path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
     path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

     path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('checkout/', CheckoutView.as_view(), name='checkout'),
     path('add-coupon/', addCouponView.as_view(), name='add-coupon'),
     path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
     path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    

     path('contact/', contact, name='contact'),
     path('send-email/', send_email, name='send_email'),
     path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter'),
     path('about/', about, name='about'),
]

tienda_audio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('core.urls', namespace='core')),

    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Hemiola Admin Panel"
admin.site.site_title = "Hemiola App Admin"
admin.site.site_index_title = "Welcome to Hemiola Admin Panel"

templates/base/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Male_Fashion Template">
    <meta name="keywords" content="Male_Fashion, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block head_title %}{% endblock %}</title>

    {% block extra_head %}
    {% endblock %}

    <link rel="shortcut icon" href="{%  static 'img/pocket.ico' %}">

    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;600;700;800;900&display=swap"
    rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

    <script>

        (function() {

            function getCookie(name) {
                var cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    var cookies = document.cookie.split(';');
                    for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            function uuidv4() {
                return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
                    let r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
                    return v.toString(16);
                });
            }            

            let device = getCookie("device");

            if(device === null || device === undefined) {
                device = uuidv4()
            } 

            document.cookie = "device=" + device + ";domain=;path=/"
        })()
    
    </script>

</head>

<body>

    <div id="preloder">
        <div class="loader"></div>
    </div>

    {% include "base/navbar.html" %}
    
    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "base/footer.html" %}

    <div class="search-model">
        <div class="h-100 d-flex align-items-center justify-content-center">
            <div class="search-close-switch">+</div>
            <form class="search-model-form" action="{% url 'core:shop' %}">
                <input type="text" id="search-input" name="search" placeholder="¿Qué buscas?...">
            </form>
        </div>
    </div>

    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/mixitup.min.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script>

        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        (function() {

            const clickeables = document.getElementsByClassName("product__item__pic")
    
            Array.from(clickeables).forEach(function(element) {
                element.addEventListener('click', event => {
                    event.preventDefault()
                    const url = element.dataset.href
                    window.location.href = url
                })
            })
        })()
    
    </script>

    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>

</html>

templates/base/footer.html
{% load static %}

{% get_categories as all_categories %}

<footer class="footer">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__logo">
                        <a href="#"><img src="{% static 'img/hemiola-dark.png' %}" alt=""></a>
                    </div>
                    <p>La música es un eco del mundo invisible.</p>
                </div>
            </div>
            <div class="col-lg-2 offset-lg-1 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Tienda</h6>
                    <ul>
                        {% for category in all_categories %}
                            <li data-filter=".{{category.slug}}"><a href="#">{{ category.name }}</a></li>
                        {% endfor %}                       
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-3 col-sm-6">
                <div class="footer__widget">
                    <h6>Sitio</h6>
                    <ul>
                        <li class="{% if request.path == '/blog/' %}active{% endif %}"><a href="{% url 'blog:list' %}">Blog</a></li>
                        <li class="{% if request.path == '/contact/' %}active{% endif %}"><a href="{% url 'core:contact' %}">Contacto</a></li>
                        <li class="{% if request.path == '/about/' %}active{% endif %}"><a href="{% url 'core:about' %}">Nosotros</a></li>
                        <li class="{% if request.path == '/shop/' %}active{% endif %}"><a href="{% url 'core:shop' %}">Tienda</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3 offset-lg-1 col-md-6 col-sm-6">
                <div class="footer__widget">
                    <h6>Novedades</h6>
                    <div class="footer__newslatter">
                        <p>¡Sé el primero en enterarte de nuestras novedades!</p>
                        <div class="newsletter-message" id="newsletter-message">                            
                            <span id="newsletter-success-message" class="newsletter-success-message">🎹 Gracias por suscribirte.</span>
                            <span id="newsletter-error-message" class="newsletter-error-message">🔥 Se produjo un error, vuelve a intentarlo por favor.</span> 
                        </div>
                        <span class="newsletter-spinner" id="newsletter-spinner"></span>
                        <form novalidate id="newsletter-form">
                            <input type="text" id="newsletter_email" name="newsletter_email" placeholder="Correo">
                            <button type="submit" id="newsletter_btn"><span class="icon_mail_alt"></span></button>
                        </form>
                    </div>                    
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="footer__copyright__text">
                    <p>Hemiola ©
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>


{% block extra_scripts %}

<script>
    (function() {

        const subscribe_newsletter_url = "{% url 'core:subscribe_newsletter' %}"
        const newsletter_btn = document.getElementById("newsletter_btn");

        newsletter_btn.addEventListener("click", function(event) {
            event.preventDefault()            
            document.getElementById("newsletter-message").style.visibility = "hidden";
            document.getElementById("newsletter-error-message").style.display = "none";
            document.getElementById("newsletter-success-message").style.display = "none";
            document.getElementById("newsletter-spinner").style.display = "none";
            const email_input = document.getElementById("newsletter_email")
            const email = email_input.value

            if(email === ""){
                email_input.classList.add("input-error");
            }else{
                email_input.classList.remove("input-error");
            }
            
            if(email){
                document.getElementById("newsletter-spinner").style.display = "inline-block";
                document.getElementById("newsletter-form").style.display = "none";
                
                fetch(subscribe_newsletter_url, {
                    credentials: 'include',
                    method: 'POST',
                    headers: {
                        "X-CSRFToken": getCookie("csrftoken"),
                        "Accept": "application/json",
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify({
                        email
                    })
                }).then(
                    response => response.json()
                ).then(function(data) {
                    if(data.success){
                        email_input.value = ""

                        document.getElementById("newsletter-error-message").style.display = "none";
                        document.getElementById("newsletter-success-message").style.display = "block";                        
                    }else{
                        document.getElementById("newsletter-error-message").style.display = "block";
                        document.getElementById("newsletter-success-message").style.display = "none";                        
                    }          
                    document.getElementById("newsletter-spinner").style.display = "none";
                    document.getElementById("newsletter-message").style.visibility = "visible";
                })      
            }
        })
    })()
</script>

{% endblock extra_scripts %}

templates/base/navbar.html
{% load static %}

{% cart_item as cart %}

<div class="offcanvas-menu-overlay"></div>
<div class="offcanvas-menu-wrapper">
    <div class="offcanvas__option">
        <div class="offcanvas__links">
            {% if user.is_authenticated %}
                <a href="{% url 'account_logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'account_login' %}">Log in</a>
                <a href="{% url 'account_signup' %}">Sign in</a>
            {% endif %}         
        </div>
        <!-- <div class="offcanvas__top__hover">
            <span>Usd <i class="arrow_carrot-down"></i></span>
            <ul>
                <li>USD</li>
                <li>EUR</li>
                <li>USD</li>
            </ul>
        </div> -->
    </div>
    <div class="offcanvas__nav__option">
        <a href="" class="search-switch"><img src="{% static 'img/icon/search.png' %}" alt=""></a>
        <!-- <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a> -->
        <a href="{% url 'core:order-summary' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> 
            <span>{{ cart.count }}</span>
        </a>
        <div class="price">{{ cart.total | currency }}</div>
    </div>
    <div id="mobile-menu-wrap"></div>
    <div class="offcanvas__text">
        <p>Envíos gratis y garantía de devolución de hasta 30 días.</p>
    </div>
</div>
<!-- Offcanvas Menu End -->

<!-- Header Section Begin -->
<header class="header">
    <div class="header__top">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-7">
                    <div class="header__top__left">
                        <p>Envíos gratis y garantía de devolución de hasta 30 días.</p>
                    </div>
                </div>
                <div class="col-lg-6 col-md-5">
                    <div class="header__top__right">
                        <div class="header__top__links">
                            {% if user.is_authenticated %}
                                <a href="{% url 'account_logout' %}">Log out</a>
                            {% else %}
                                <a href="{% url 'account_login' %}">Log in</a>
                                <a href="{% url 'account_signup' %}">Sign in</a>
                            {% endif %}         
                        </div>
                        <!-- <div class="header__top__hover">
                            <span>Usd <i class="arrow_carrot-down"></i></span>
                            <ul>
                                <li>USD</li>
                                <li>EUR</li>
                                <li>USD</li>
                            </ul>
                        </div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-3">
                <div class="header__logo">
                    <a href="{% url 'core:home' %}"><img src="{% static 'img/hemiola.png' %}" alt=""></a>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <nav class="header__menu mobile-menu">
                    <ul>
                        <li class="{% if request.path == '/' %}active{% endif %}"><a href="{% url 'core:home' %}">Inicio</a></li>
                        <li class="{% if request.path == '/shop/' %}active{% endif %}"><a href="{% url 'core:shop' %}">Tienda</a></li>
                        <li class="{% if request.path == '/blog/' %}active{% endif %}"><a href="{% url 'blog:list' %}">Blog</a></li>
                        <li class="{% if request.path == '/contact/' %}active{% endif %}"><a href="{% url 'core:contact' %}">Contacto</a></li>
                        <li class="{% if request.path == '/about/' %}active{% endif %}"><a href="{% url 'core:about' %}">Nosotros</a></li>
                    </ul>
                </nav>
            </div>
            <div class="col-lg-3 col-md-3">
                <div class="header__nav__option">
                    <a href="#" class="search-switch">
                        <img src="{% static 'img/icon/search.png' %}" alt="">
                    </a>
                    <!-- <a href="#"><img src="{% static 'img/icon/heart.png' %}" alt=""></a> -->
                    <a href="{% url 'core:order-summary' %}"><img src="{% static 'img/icon/cart.png' %}" alt=""> 
                        <span>{{ cart.count }}</span>
                    </a>
                    <div class="price">{{ cart.total | currency }}</div>
                </div>
            </div>
        </div>
        <div class="canvas__open"><i class="fa fa-bars"></i></div>
    </div>
</header>

templates/base/scripts.html
{% load static %}

<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Font Awesome Pro -->
<script type="text/javascript" src="{% static 'js/font_awesome.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>