blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, by_tag, by_category

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path
from .views import HomeView, ShopView, CheckoutView, OrderSummaryView, ItemDetailView, about, contact,add_to_cart, add_single_item_to_cart, \
     remove_from_cart, remove_single_item_from_cart, PaymentView, addCouponView, RequestRefundView, send_email, subscribe_newsletter

app_name = 'core'

urlpatterns = [
     path('', HomeView.as_view(), name='home'),
     path('shop/', ShopView.as_view(), name='shop'),
     path('product/<slug>/', ItemDetailView.as_view(), name='product'),

     path('add-single-item-to-cart/<slug>/', add_single_item_to_cart, name='add-single-item-to-cart'),
     path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
     path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
     path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

     path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('checkout/', CheckoutView.as_view(), name='checkout'),
     path('add-coupon/', addCouponView.as_view(), name='add-coupon'),
     path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
     path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    

     path('contact/', contact, name='contact'),
     path('send-email/', send_email, name='send_email'),
     path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter'),
     path('about/', about, name='about'),
]

tienda_audio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('core.urls', namespace='core')),

    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Hemiola Admin Panel"
admin.site.site_title = "Hemiola App Admin"
admin.site.site_index_title = "Welcome to Hemiola Admin Panel"

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.contrib.staticfiles.templatetags.staticfiles import static

class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    list_image = models.ImageField(upload_to='blog/', blank=True, null=True)
    detail_image = models.ImageField(upload_to='blog/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL)
    # tags = 
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = TaggableManager(blank=True)

    @property
    def author_image(self):
        image_url = static('img/default.png')
        if self.author and self.author.profile and self.author.profile.image:
            image_url = self.author.profile.image.url
        return image_url

    @property
    def list_image_url(self):
        image_url = static('img/list-default.jpg')
        if self.list_image:
            image_url = self.list_image.url
        return image_url

    @property
    def detail_image_url(self):
        image_url = static('img/detail-default.jpg')
        if self.detail_image:
            image_url = self.detail_image.url
        return image_url        

    def __str__(self):
        return self.title

class Category(models.Model):
    name = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    website = models.CharField(max_length=50, blank=True, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def author_name(self):
        return self.author or self.name

    @property
    def author_image(self):
        image_url = static('img/default.png')
        if self.author and self.author.profile and self.author.profile.image:
            image_url = self.author.profile.image.url
        return image_url

    def __str__(self):
        return "Comment by {}".format(self.author)

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'name',
            'email',
            'website',
            'content'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Nombre'},),
            'email': forms.TextInput(attrs={'placeholder': 'Email'},),
            'website': forms.TextInput(attrs={'placeholder': 'Sitio web'},),
            'content': forms.Textarea(attrs={'placeholder': 'Comentario'},)
        }
    

blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from django.db.models import Q
from .models import Post, Category
from taggit.models import Tag
from .forms import CommentForm
from django.views.generic import ListView, DetailView


class BlogListView(ListView):
    model = Post
    template_name = 'blog/list.html'

    def get_queryset(self):
        category_pk = self.request.GET.get('category', None)
        tag_slug = self.request.GET.get('tag', None)

        if category_pk:
            return Post.objects.filter(category__pk=category_pk).order_by("title")
        elif tag_slug:
            return Post.objects.filter(tags__name__in=[tag_slug]).order_by("title")
            
        return Post.objects.order_by("title")

def blog_list(request):
    posts = Post.objects.all()

    search = request.GET.get('search')
    if search:
        posts = posts.filter(
            Q(title__icontains=search) | 
            Q(content__icontains=search) | 
            Q(tags__name__icontains=search)
        ).distinct()

    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    posts = paginator.get_page(page)

    context = {'posts': posts}

    return render(request, 'blog/list.html', context)

class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'    

    def get_context_data(self, *args, **kwargs):
        context = super(BlogDetailView, self).get_context_data(**kwargs)
        context['form'] = CommentForm()       
        print(context)
        return context

    def post(self, *args, **kwargs):
        form = CommentForm(self.request.POST or None)
        if form.is_valid():
            comment = form.save(commit=False)
            self.object = self.get_object()
            post = self.object
            comment.post = post

            if self.request.user.is_authenticated:
                comment.author = self.request.user
            else:
                name = form.cleaned_data.get('name')
                email = form.cleaned_data.get('email')
                website = form.cleaned_data.get('website')
                comment.name = name
                comment.email = email
                comment.website = website
                
            comment.save()
            context = super().get_context_data(**kwargs)
            return self.render_to_response(context=context)
  

def blog_detail(request, id):
    post = Post.objects.get(id=id)
    categories = Category.objects.all()
    tags = Tag.objects.all()

    form = CommentForm()

    if request.method == 'POST':
        form = CommentForm(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()

    context = {'post': post, 'categories': categories, 'tags': tags, 'form': form}
    return render(request, 'blog/detail.html', context)

def by_tag(request, tag):
    posts = Post.objects.filter(tags__name__in=[tag])
    context = {'posts': posts}

    return render(request, 'blog/list.html', context)

def by_category(request, category):
    posts = Post.objects.filter(category__name=category)
    context = {'posts': posts}

    return render(request, 'blog/list.html', context)

blog/templates/blog/detail.html
{% extends "base/base.html" %}

{% load static %}

{% block content %}

<section class="breadcrumb-option">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb__text">
					<h4>Blog</h4>
					<div class="breadcrumb__links">
						<a href="{% url 'core:home' %}">Inicio</a>
						<span>Blog</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="blog-hero spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-9 text-center">
                <div class="blog__hero__text">
                    <h2>{{ object.title }}</h2>
                    <ul>
                        <li>
                            <div class="blog__details__post__author__pic">
                                <img src="{{ object.author_image }}" alt="">
                            </div> {{ object.author }}
                        </li>
                        <li>{{ object.created_at | date:"d F Y"}}</li>
                        <li>{{ object.comments.count }} Comentario{{ object.comments.count | pluralize }}</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="blog-details spad">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-lg-12">
                <div class="blog__details__pic">
                    <img src="{{ object.detail_image_url }}" alt="">
                </div>
            </div>
            <div class="col-lg-8">
                <div class="blog__details__content">
                    <!-- <div class="blog__details__share">
                        <span>share</span>
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#" class="youtube"><i class="fa fa-youtube-play"></i></a></li>
                            <li><a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a></li>
                        </ul>
                    </div> -->
                    <div class="blog__details__text">
                        <div class="row">
                            <p class="blog__details__content">{{ object.content | safe }}</p>
                        </div>
                    </div>
                    <div class="blog__details__option">
                        <div class="row">
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__category">
                                    <a href="{% url 'blog:list' %}?category={{ object.category.id }}">
                                        {{ object.category }}
                                    </a>
                                </div>
                            </div>
                            <div class="col-lg-6 col-md-6 col-sm-6">
                                <div class="blog__details__tags">
                                    {% for tag in object.tags.all %}
                                        <a href="{% url 'blog:list' %}?tag={{ tag.slug }}">#{{ tag }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="blog__details__option">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <ul class="comment-list">
                                    {% for comment in post.comments.all %}
                                        <li class="comment">
                                            <div class="blog__details__author__pic">
                                                <img src="{{ comment.author_image }}" alt="">
                                            </div>
                                            <div class="blog__details__author__text">
                                                <h5>{{ comment.author_name }}</h5>
                                            </div>
                                            <div class="comment-body">
                                                <p>{{ comment.content | linebreaks }}</p>
                                                <div class="meta">{{ comment.created_at }}</div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>                                                   
                        </div>
                    </div>

                    <div class="blog__details__comment">
                        <h4>Deja un comentario</h4>
                        <form method="POST">
                            {% csrf_token %}
                            <div class="row">
                                {% if not user.is_authenticated %}
                                    <div class="col-lg-4 col-md-4">
                                        {{ form.name }}
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        {{ form.email }}
                                    </div>
                                    <div class="col-lg-4 col-md-4">
                                        {{ form.website }}
                                    </div>
                                {% endif %}
                                <div class="col-lg-12 text-center">
                                    {{ form.content }}
                                    <button type="submit" class="site-btn">Comentar</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

blog/templates/blog/list.html
{% extends "base/base.html" %}

{% load static %}

{% block content %}

<section class="breadcrumb-option">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb__text">
					<h4>Blog</h4>
					<div class="breadcrumb__links">
						<a href="{% url 'core:home' %}">Inicio</a>
						<span>Blog</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="breadcrumb-blog set-bg" data-setbg="{% static 'img/breadcrumb-bg.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h2>Nuestro Blog</h2>
            </div>
        </div>
    </div>
</section>

<section class="blog spad">
    <div class="container">
        <div class="row">
            {% for post in object_list %}
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="blog__item">
                        <a href="{% url 'blog:detail' post.id %}">
                            <div class="blog__item__pic set-bg" data-setbg="{{ post.list_image_url }}"></div>
                        </a>
                        <div class="blog__item__text">
                            <span>
                                <img src="{% static 'img/icon/calendar.png' %}" alt=""> {{ post.created_at | date:"d F Y"}}
                            </span>
                            <a href="{% url 'blog:detail' post.id %}">
                                <h5>{{ post.title }}</h5>
                            </a>
                            <a class="blog__item__text__a" href="{% url 'blog:detail' post.id %}">Leer más</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}