blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView, by_tag, by_category

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='list'),
    path('<int:pk>', BlogDetailView.as_view(), name='detail'),
]

core/urls.py
from django.urls import path
from .views import HomeView, ShopView, CheckoutView, OrderSummaryView, ItemDetailView, about, contact,add_to_cart, add_single_item_to_cart, \
     remove_from_cart, remove_single_item_from_cart, PaymentView, addCouponView, RequestRefundView, send_email, subscribe_newsletter

app_name = 'core'

urlpatterns = [
     path('', HomeView.as_view(), name='home'),
     path('shop/', ShopView.as_view(), name='shop'),
     path('product/<slug>/', ItemDetailView.as_view(), name='product'),

     path('add-single-item-to-cart/<slug>/', add_single_item_to_cart, name='add-single-item-to-cart'),
     path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
     path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
     path('remove-single-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),

     path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
     path('checkout/', CheckoutView.as_view(), name='checkout'),
     path('add-coupon/', addCouponView.as_view(), name='add-coupon'),
     path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
     path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    

     path('contact/', contact, name='contact'),
     path('send-email/', send_email, name='send_email'),
     path('subscribe-newsletter/', subscribe_newsletter, name='subscribe_newsletter'),
     path('about/', about, name='about'),
]

tienda_audio/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('', include('core.urls', namespace='core')),

    path('summernote/', include('django_summernote.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = "Hemiola Admin Panel"
admin.site.site_title = "Hemiola App Admin"
admin.site.site_index_title = "Welcome to Hemiola Admin Panel"

core/models.py
from django.db.models.signals import post_save
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from taggit.managers import TaggableManager
from django.utils import timezone
import PIL.Image
from django.contrib.staticfiles.templatetags.staticfiles import static
from django.utils.timezone import now
from django.utils.text import slugify
import os

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping')
)


class Customer(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, related_name="customer")
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)
    device = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        if self.user:
            name = self.user
        else:
            name = self.device
        return str(name)

def get_upload_path(instance, filename):
    model = instance.album.model.__class__._meta
    name = model.verbose_name_plural.replace(' ', '_')
    return f'{name}/images/{filename}'

class ImageAlbum(models.Model):
    def default(self):
        return self.images.filter(default=True).first()
    def thumbnails(self):
        return self.images.filter(width__lt=100, length__lt=100)

    def __str__(self):
        if hasattr(self, 'model'):
            return f"{self.model}'s album"
        else:
            return f"Empty album #{self.id}"
            

class Image(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to=get_upload_path)
    default = models.BooleanField(default=False)
    width = models.FloatField(default=100)
    length = models.FloatField(default=100)
    album = models.ForeignKey(ImageAlbum, related_name='images', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} from {self.album}"

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=1000, blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'

class Brand(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.CharField(max_length=1000, blank=True, null=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Item(models.Model):
    title = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True, related_name='items')
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True, related_name='items')
    label = models.CharField(choices=LABEL_CHOICES, max_length=1, default='P')
    slug = models.SlugField(max_length=50, blank=True, null=True)
    description = models.TextField(default="Description")
    image = models.ImageField(default="default.jpg")
    album = models.OneToOneField(ImageAlbum, related_name='model', on_delete=models.CASCADE, null=True, blank=True)
    tags = TaggableManager(blank=True)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if not self.slug and self.title:
            self.slug = slugify(self.title)      
        super(Item, self).save(*args, **kwargs)                  

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def get_antiquity(self):
        return int((timezone.now() - self.created_at).days)

    def get_label(self):
        if self.get_antiquity() < 30:
            return "Nuevo"
        elif self.discount_price:
            return "Rebaja"
        return None

    def get_label_class(self):
        if self.get_antiquity() < 30:
            return "new"
        elif self.discount_price:
            return "sale"
        return None

    def related_items(self):
        tags_ids = list(self.tags.values_list('pk', flat=True))
        items = Item.objects.filter(tags__pk__in=(tags_ids)).exclude(pk=self.pk).order_by('-created_at').distinct()[:4]        
        if items.count() < 4:
            limit = (4 - items.count())
            extra = self.category.items.exclude(pk=self.pk).order_by('-created_at')[:limit]
            items = items | extra

        return items

class Review(models.Model):
    author = models.ForeignKey(Customer, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    website = models.CharField(max_length=50, blank=True, null=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='reviews')
    content = models.TextField()
    stars = models.IntegerField(default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    @property
    def author_name(self):
        return self.author or self.name

    @property
    def author_image(self):
        image_url = static('img/default.png')
        if self.author and self.author.user and self.author.user.profile:
            image_url = self.author.user.profile.image.url
        return image_url

    def __str__(self):
        return "Review by {}".format(self.author_name)


class OrderItem(models.Model):
    customer = models.ForeignKey(Customer,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_ammount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        else:
            return self.get_total_item_price()


class Order(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField(default=now)
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer}'s' order"

    def get_sub_total(self):
        sub_total = 0
        for order_item in self.items.all():
            sub_total += order_item.get_final_price()

        return sub_total

    def get_total(self):
        total = self.get_sub_total()
        if self.coupon and total > 0:
            total -= self.coupon.amount
        return total


class Address(models.Model):
    customer = models.ForeignKey(Customer,
                             on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100, blank=True, null=True)
    last_name = models.CharField(max_length=100, blank=True, null=True)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    phone = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.customer}'s' address"

    class Meta:

templates/about.html
{% extends "base/base.html" %}

{% load static %}

{% block content %}

<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Nosotros</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'core:home' %}">Inicio</a>
                        <span>Nosotros</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="about spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="about__pic">
                    <img src="{% static 'img/about/about-us.jpg' %}" alt="">
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>¿Quiénes somos?</h4>
                    <p>Contextual advertising programs sometimes have strict policies that need to be adhered too.
                    Let’s take Google as an example.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>¿Qué hacemos?</h4>
                    <p>In this digital generation where information can be easily obtained within seconds, business
                    cards still have retained their importance.</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-4 col-sm-6">
                <div class="about__item">
                    <h4>¿Por qué elegirnos?</h4>
                    <p>A two or three storey house is the ideal way to maximise the piece of earth on which our home
                    sits, but for older or infirm people.</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- About Section End -->

<!-- Testimonial Section Begin -->
<section class="testimonial">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-6 p-0">
                <div class="testimonial__text">
                    <span class="icon_quotations"></span>
                    <p>“La gente dice que nosotros nos tomamos las cosas muy en serio, pero es la única forma en la cual llegas a algún lugar”.</p>
                    <div class="testimonial__author">
                        <div class="testimonial__author__pic">
                            <img src="{% static 'img/about/testimonial-author.jpg' %}" alt="">
                        </div>
                        <div class="testimonial__author__text">
                            <h5>Thomas Edward Yorke</h5>
                            <p>Tchock</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 p-0">
                <div class="testimonial__pic set-bg" data-setbg="{% static 'img/about/testimonial-pic.jpg' %}"></div>
            </div>
        </div>
    </div>
</section>
<!-- Testimonial Section End -->

<!-- Client Section Begin -->
<section class="clients spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <span>Nuestras Marcas</span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="https://teenage.engineering/" class="client__item" target="_blank"><img src="{% static 'img/clients/client-1.png' %}" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="https://www.moogmusic.com/" class="client__item" target="_blank"><img src="{% static 'img/clients/client-2.png' %}" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="https://www.korg.com/es/" class="client__item" target="_blank"><img src="{% static 'img/clients/client-3.png' %}" alt=""></a>
            </div>
            <div class="col-lg-3 col-md-4 col-sm-4 col-6">
                <a href="https://www.sequential.com/" class="client__item" target="_blank"><img src="{% static 'img/clients/client-4.png' %}" alt=""></a>
            </div>            
        </div>
    </div>
</section>

{% endblock content %}

templates/order_summary.html
{% extends "base/base.html" %}

{% block content %}

<section class="breadcrumb-option">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="breadcrumb__text">
                    <h4>Mi Carro</h4>
                    <div class="breadcrumb__links">
                        <a href="{% url 'core:home' %}">Inicio</a>
                        <a href="{% url 'core:shop' %}">Tienda</a>
                        <span>Mi Carro</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="shopping-cart spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="shopping__cart__table">
                    <table>
                        <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Cantidad</th>
                                <th>Total</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order_item in object.items.all %}
                            <tr>
                                <td class="product__cart__item">
                                    <div class="product__cart__item__pic">
                                        <a href="{{ order_item.item.get_absolute_url }}">
                                            <img src="{{ order_item.item.image.url }}" width="90" alt="">
                                        </a>
                                    </div>
                                    <div class="product__cart__item__text">
                                        <a href="{{ order_item.item.get_absolute_url }}"><h6>{{ order_item.item.title }}</h6></a>
                                        {% if order_item.item.discount_price %}
                                            <h5>{{ order_item.item.discount_price | currency }}</h5>
                                        {% else %}
                                            <h5>{{ order_item.item.price | currency }}</h5>
                                        {% endif %}
                                    </div>
                                </td>
                                <td class="quantity__item">
                                    <div class="quantity">
                                        <div class="pro-qty-2">
                                            <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}">
                                                <span class="fa fa-angle-left dec qtybtn"></span>
                                            </a>

                                            <input type="text" value="{{ order_item.quantity }}">

                                            <a href="{% url 'core:add-single-item-to-cart' order_item.item.slug %}">
                                                <span class="fa fa-angle-right inc qtybtn"></span>
                                            </a>                                            
                                        </div>
                                    </div>
                                </td>
                                <td class="cart__price">{{ order_item.get_final_price | currency }}</td>
                                <td class="cart__close">
                                    <a href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                                        <i class="fa fa-close"></i>
                                    </a>
                                </td>
                            </tr>
                            {% empty %}
                            <tr>
                                <td colspan="4">Tu carro está vacío</td>
                            </tr>
                            {% endfor %}                            
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn">
                            <a href="{% url 'core:shop' %}">{% if object.items.count %}Seguir comprando{% else %}Empezar a comprar{% endif %}</a>
                        </div>
                    </div>
                    <!-- <div class="col-lg-6 col-md-6 col-sm-6">
                        <div class="continue__btn update__btn">
                            <a href="#"><i class="fa fa-spinner"></i> Update cart</a>
                        </div>
                    </div> -->
                </div>
            </div>
            <div class="col-lg-4">
                {% if object.items.count and not object.coupon %}
                    <div class="cart__discount">
                        <h6>Cupón de descuento</h6>
                        <form action="{% url 'core:add-coupon' %}" method="POST">
                            {% csrf_token %}
                            {{ couponForm.code }}
                            <button type="submit">Aplicar</button>
                        </form>                    
                    </div>
                {% endif %}
                <div class="cart__total">
                    <h6>A pagar</h6>
                    <ul>
                        {% if object.items.count %}
                            <li>Sub Total <span>{{ object.get_sub_total | currency }}</span></li>
                            {% if object.coupon %}
                                <li class="text-success">
                                    Promo {{ object.coupon.code }}<span class="text-success"> -{{ object.coupon.amount | currency }}</span>
                                </li>
                            {% endif %}                            
                        {% endif %}
                        <li>Total <span>{{ object.get_total | currency }}</span></li>
                    </ul>
                    {% if object.items.count %}
                        <a href="{% url 'core:checkout' %}" class="primary-btn">Proceder con el pago</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/request_refund.html
{% extends "base/base.html" %}

{% load crispy_forms_tags %}

{% block content %}

<main>
    <div class="container">

        <h2>Request Refund</h2>

        <form method="POST">
            {% csrf_token %}

            {{ form | crispy }}

            <button class="btn btn-primary" type="submit">Submit</button>

        </form>

    </div>
</main>

{% endblock content %}

templates/shop.html
{% extends "base/base.html" %} 
{% load static %} 
{% block content %} 
{% get_categories_total as categories_filter %} 
{% get_brands_total as brands_filter %}
{% get_popular_tags as tags_filter %}

<section class="breadcrumb-option">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="breadcrumb__text">
					<h4>Tienda</h4>
					<div class="breadcrumb__links">
						<a href="{% url 'core:home' %}">Home</a>
						<span>Tienda</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="shop spad">
	<div class="container">
		<div class="row">
			<div class="col-lg-3">
				<div class="shop__sidebar">
					<div class="shop__sidebar__search">
						<form action="#">
							<input type="text" value="{{ search }}" name="search" placeholder="Buscar..." />
							<button type="submit">
								<span class="icon_search"></span>
							</button>
						</form>
					</div>
					<div class="shop__sidebar__accordion">
						<div class="accordion" id="accordionExample">
							<div class="card">
								<div class="card-heading">
									<a data-toggle="collapse" data-target="#collapseOne">Categorías</a>
								</div>
								<div id="collapseOne" class="collapse show" data-parent="#accordionExample">
									<div class="card-body">
										<div class="shop__sidebar__categories">
											<ul class="nice-scroll">
												{% for category in categories_filter %}
												<li class="{% ifequal category.slug category_slug %}active{% endifequal %}">
													<a href="{% url 'core:shop' %}?category={{ category.slug }}">
														{{ category.name }} ({{category.items_count }})
													</a>
												</li>												
												{% endfor %}
												{% if category_slug %}
												<li>
													<a href="{% url 'core:shop' %}">
														Limpiar
													</a>
												</li>
												{% endif %}
											</ul>
										</div>
									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-heading">
									<a data-toggle="collapse" data-target="#collapseTwo">Marcas</a>
								</div>
								<div id="collapseTwo" class="collapse show" data-parent="#accordionExample">
									<div class="card-body">
										<div class="shop__sidebar__brand">
											<ul>
												{% for brand in brands_filter %}
												<li class="{% ifequal brand.slug brand_slug %}active{% endifequal %}">
													<a href="{% url 'core:shop' %}?brand={{ brand.slug }}">
														{{ brand.name }} ({{brand.items_count }})
													</a>
												</li>
												{% endfor %}
												{% if brand_slug %}
												<li>
													<a href="{% url 'core:shop' %}">
														Limpiar
													</a>
												</li>
												{% endif %}
											</ul>
										</div>
									</div>
								</div>
							</div>
							<!-- <div class="card">
                                <div class="card-heading">
                                    <a data-toggle="collapse" data-target="#collapseThree">Filter Price</a>
                                </div>
                                <div id="collapseThree" class="collapse show" data-parent="#accordionExample">
                                    <div class="card-body">
                                        <div class="shop__sidebar__price">
                                            <ul>
                                                <li><a href="#">$0.00 - $50.00</a></li>
                                                <li><a href="#">$50.00 - $100.00</a></li>
                                                <li><a href="#">$100.00 - $150.00</a></li>
                                                <li><a href="#">$150.00 - $200.00</a></li>
                                                <li><a href="#">$200.00 - $250.00</a></li>
                                                <li><a href="#">250.00+</a></li>
                                            </ul>
                                        </div>
                                    </div>
                                </div>
                            </div>                             -->
							<div class="card">
								<div class="card-heading">
									<a data-toggle="collapse" data-target="#collapseSix">Etiquetas</a>
								</div>
								<div id="collapseSix" class="collapse show" data-parent="#accordionExample">
									<div class="card-body">
										<div class="shop__sidebar__tags">
											{% for tag in tags_filter %}
											<a class="{% ifequal tag.slug tag_slug %}active{% endifequal %}" href="{% url 'core:shop' %}?tag={{ tag.slug }}">
												{{ tag.name }}
											</a>
											{% endfor %}
											{% if tag_slug %}
												<br />												
												<a href="{% url 'core:shop' %}">
													Limpiar
												</a>												
											{% endif %}
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-9">
				<div class="shop__product__option">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-sm-6">
							<div class="shop__product__option__left">
								{% if is_paginated %}
									<p>Mostrando {{ page_obj.start_index }}-{{ page_obj.end_index }} de {{ page_obj.paginator.count }} resultados</p>
								{% else %}
									<p>Mostrando 1-{{ item_list.count }} de {{ item_list.count }} resultados</p>
								{% endif %}
							</div>
						</div>
						<!-- <div class="col-lg-6 col-md-6 col-sm-6">
							<div class="shop__product__option__right">
								<p>Sort by Price:</p>
								<select>
									<option value="">Low To High</option>
									<option value="">$0 - $55</option>
									<option value="">$55 - $100</option>
								</select>
							</div>
						</div> -->
					</div>
				</div>
				<div class="row">
					{% for item in item_list %}					
						<div class="col-lg-4 col-md-6 col-sm-6">
							<div class="product__item sale">
								<div class="product__item__pic set-bg" data-href="{{ item.get_absolute_url }}" data-setbg="{{ item.image.url }}">
									{% if item.get_label %}
										<span class="label-{{ item.get_label_class }}">
											{{ item.get_label }}
										</span>
									{% endif %}
									<!-- <ul class="product__hover">
										<li>
											<a href="#">
												<img src="{% static 'img/icon/heart.png' %}" alt="" />
											</a>
										</li>
										<li>
											<a href="{{ item.get_absolute_url }}">
												<img src="{% static 'img/icon/search.png' %}" alt="" />
											</a>
										</li>
									</ul> -->
								</div>
							
								<div class="product__item__text">
									<h6>{{ item.title }}</h6>
									<h6>{{ item.subtitle }}</h6>
									<a href="{{ item.get_add_to_cart_url }}" class="add-cart">+ Agregar al Carro</a>
									<!-- <div class="rating">
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star"></i>
										<i class="fa fa-star-o"></i>
									</div> -->
									<h5>										
										{% if item.discount_price %} 
											{{ item.discount_price | currency }}
										{% else %} 
											{{ item.price | currency }} 
										{% endif %}
									</h5>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>

				{% include "partials/pagination.html" %}
			</div>
		</div>
	</div>
</section>

{% endblock content %}